// Generated by CoffeeScript 1.3.1
var default_config;

default_config = {
  elementId: "vizdiv",
  gexf: "bib.gexf",
  path: "js/tinaviz/",
  assets: "",
  embed: false,
  view: "macro",
  category_a_label: "NGram",
  category_b_label: "Document",
  category: "Document",
  node_id: "",
  search: "",
  a_node_size: 0.50,
  b_node_size: 0.50,
  cursor_size: 0.01,
  a_edge_filter_min: 0.0,
  a_edge_filter_max: 1.0,
  a_node_filter_min: 0.0,
  a_node_filter_max: 1.0,
  b_edge_filter_min: 0.0,
  b_edge_filter_max: 1.0,
  b_node_filter_min: 0.0,
  b_node_filter_max: 1.0,
  layout: "tinaforce",
  layout_speed: 30,
  antialiasing_threshold: 1500,
  pause: false,
  demo: false,
  experimental: false
};
